spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ecommerce
        username: postgres
        password: postgre
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp